version: '3.8'

services:
  mailing_db:
    image: postgres:15
    container_name: mailing_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mailing_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - mailing_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "mailing_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  core-service:
    build:
      context: ./core-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://mailing_db:5432/mailing_db
      DB_USERNAME: user
      DB_PASSWORD: pass
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    volumes:
      - ./core-service/src/main/resources/application-docker.yml:/app/config/application.yml
    depends_on:
      mailing_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3

  smtp-mail-service:
    build:
      context: ./smtp-mail-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    volumes:
      - ./smtp-service/src/main/resources/application-docker.yml:/app/config/application.yml
    depends_on:
      core-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3

  answering-service:
    build:
      context: ./answering-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://mailing_db:5432/mailing_db
      DB_USERNAME: user
      DB_PASSWORD: pass
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    volumes:
      - ./answering-service/src/main/resources/application-docker.yml:/app/config/application.yml
    depends_on:
      core-service:
        condition: service_healthy


volumes:
  mailing_db:
