server:
  port: 8083
spring:
  main:
    web-application-type: none


  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

  application:
    name: smtp-mail-service

  datasource:
    url: jdbc:postgresql://localhost:5432/mailing_db
    username: user
    password: pass

  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

    smtpMailQueue: smtpStatusQueue
    coreServiceQueue: coreServiceQueue
