server:
  port: 8081

spring:
  application:
    name: answering-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

  datasource:
    url: jdbc:postgresql://localhost:5432/mailing_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 1
      connection-timeout: 5000
      minimum-idle: 5
      auto-commit: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queueName: answeringServiceQueue

